export const daysOff = new Map([
  ['Nyårsdagen', true],
  ['Trettondedag jul', true],
  ['Skärtorsdag', false],
  ['Långfredagen', true],
  ['Påskafton', true],
  ['Påskdagen', true],
  ['Annandag påsk', true],
  ['Första maj', true],
  ['Kristi Himmelsfärdsdag', true],
  ['Pingstdagen', false],
  ['Annandag pingst', false],
  ['Sveriges nationaldag', true],
  ['Midsommarafton', true],
  ['Midsommardagen', true],
  ['Alla helgons dag', true],
  ['Julafton', true],
  ['Juldagen', true],
  ['Annandag jul', true],
  ['Nyårsafton', true],
])
